In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame({"name":["fati","noor","devil","satan"],'age':[23,4,6,7]})
print(df)

    name  age
0   fati   23
1   noor    4
2  devil    6
3  satan    7

In [2]:
df1=pd.DataFrame(np.random.randn(20,3),
                 columns=['a','b','c'],
                 index=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(df1)

           a         b         c
1   0.495397  0.877259  1.162158
2   1.063776 -0.488580 -0.809708
3  -0.112315  1.784694  1.366068
4  -0.424038 -0.670641  0.613316
5   1.818808  1.362631 -0.139665
6  -0.802216  1.131822  0.639289
7   0.788718 -0.118713 -0.525215
8   0.569801 -0.022632 -0.202448
9   0.608005  0.120971 -0.753244
10 -0.288996  1.163866  0.956914
11  1.615566  1.740742  0.323542
12 -1.672922 -0.867298  1.445252
13  1.199756  0.253169  0.193620
14  2.159351 -2.255405  1.158972
15 -0.523381 -0.489714  0.667753
16 -0.079260  0.602535 -1.344452
17 -0.499099  0.443183  0.851753
18 -0.991481 -0.924299 -1.654895
19  1.160181 -0.365026 -0.717968
20 -1.426840 -0.930597  0.847216

In [3]:
f2 = pd.DataFrame([
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'},
    {'Name' :'hamza','Age':34,'City':'gujranwala'}])
print(f2)
#print(f2.shape)
#print(f2.info())
#f2.describe() #numerical data py kam krta hai,quick statistical view provide krta hai
print(f2.iloc[1:2])

    Name  Age        City
0  Alice   25    New York
1    Bob   30       Paris
2  hamza   34  gujranwala
  Name  Age   City
1  Bob   30  Paris

In [4]:
#csv-CSV ek simple text file hoti hai jisme table jaisa data commas se separate hota hai.
from io import StringIO
df2=StringIO("Name,Sallary,Age \n fatima, 445632,21\n noor,223242,20 ")
data=pd.read_csv(df2)
print(data)

      Name  Sallary  Age
0   fatima   445632    21
1     noor   223242    20

CSV pandas ka method nahi hai.
CSV ek file format hai.
CSV kya hai?
Ek file type
Extension: .csv
Table data store karti hai
Pandas kya karta hai?
Pandas ke paas methods hote hain jo CSV ko:
Read karte hain
Write karte hain
CSV read karne ka method:
pd.read_csv("file.csv")
CSV save karne ka method:
df.to_csv("file.csv")

In [5]:
dept=pd.DataFrame({'Name':['fatima','hamza','wajiha','ali','hafsa','maham','shehriyar','haris','huda','ahsan'],
'Age':[21,23,34,43,33,24,25,27,20,30],'Salary':[40000,34000,54000,40000,50000,67000,87000,45000,55000,60000],
'Department':['IT','HR','TECH','IT','HR','FINANCE','FINANCE','HR','IT','IT']})
#NAME and salary for all rows
#print(dept)
#print(dept[['Name','Salary']])
#print(dept.loc[: , 'Name'])
#print(dept[(dept['Department'] =='IT') & (dept['Age']>30)])
#print(dept['Department'].nunique())
#print(dept['Department'].nunique())
#print(dept['Department'].value_counts())
#print(dept['Age'].value_counts())
#age=dept.sort_values('Age')
#print(age)
dept_map={'IT':'INFORMATON TECH','HR':'HUMAN RESOURCE'}
dept['dept_full'] = dept['Department'].map(dept_map)
dept

        Name  Age  Salary Department        dept_full
0     fatima   21   40000         IT  INFORMATON TECH
1      hamza   23   34000         HR   HUMAN RESOURCE
2     wajiha   34   54000       TECH              NaN
3        ali   43   40000         IT  INFORMATON TECH
4      hafsa   33   50000         HR   HUMAN RESOURCE
5      maham   24   67000    FINANCE              NaN
6  shehriyar   25   87000    FINANCE              NaN
7      haris   27   45000         HR   HUMAN RESOURCE
8       huda   20   55000         IT  INFORMATON TECH
9      ahsan   30   60000         IT  INFORMATON TECH

In [6]:
x=[4,6,8,2,1,13,14]
s=pd.Series(x,index=('a','b','c','d','e','f','g'), name="my data")
s['d']

np.int64(2)

In [29]:
df=pd.read_csv("D:\Python Notebooks\weather.csv")
#df.MinTemp.replace(8.0,10,inplace=False)
#df['Rainfall'].dropna() #dropping null values
#df_mean=df["Pressure9am"].mean()
#df["Pressure9am"].fillna(df_mean) #datafram mai jaha jaha null values hai data set ka mean nikl ky use unki jaga fill kr do isi trha mode and median b hai
#df['WindGustDir']=pd.to_numeric(df['WindGustDir'], errors='coerce') #WindGusrDir mai string data para hova is lie func uski jaga NULL rkhva dy ga numeric cant convert string
#for x in df.index :
 #   if df.loc[x,'Rainfall'] > 0 :
  #    df.loc[x,'Rainfall'] = 0 
#df.duplicated() #chk for duplicates and return bool values kia pori row kisi previous wali sy match krti hai 
#df.select_dtypes(include='number').corr() #corr() numeric data py kam krta hai so use select krna zruri hai
#df.loc[df.Rainfall==39.8]# condition ky sath acess krna 
#df.loc[df.Cloud9am.isin([6,7])] # jaha cloud9am mai 6,7 ho ya in ky dramia koi cheez
#df.loc[df.Temp9am.notnull()] #jaha jaha null na ho
#df=df.rename(columns={'Rainfall':'Time'})# to rename change
#df=df.rename(index={0:1}) #renaming row name
df.groupby(['MinTemp']).MinTemp.agg([len])

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\People Links Laptop\AppData\Local\Temp\ipykernel_17464\2810291726.py:1: SyntaxWarning: invalid escape sequence '\P'
  df=pd.read_csv("D:\Python Notebooks\weather.csv")

         len
MinTemp
-5.3       1
-3.7       2
-3.5       2
-3.4       1
-3.3       1
...      ...
 17.9      2
 18.0      1
 18.2      1
 19.9      1
 20.9      1

[180 rows x 1 columns]